import abjad


performer_inventory = abjad.instrumenttools.PerformerList(
    [
        abjad.instrumenttools.Performer(
            name='oboist',
            instruments=abjad.instrumenttools.InstrumentList(
                [
                    abjad.instrumenttools.Oboe(
                        name='oboe',
                        short_name='ob.',
                        name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Oboe'
                                    ),
                                ),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Ob.'
                                    ),
                                ),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='treble',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[Bb3, A6]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    ]
                ),
            ),
        abjad.instrumenttools.Performer(
            name='clarinetist',
            instruments=abjad.instrumenttools.InstrumentList(
                [
                    abjad.instrumenttools.ClarinetInBFlat(
                        name='clarinet in B-flat',
                        short_name='cl. in B-flat',
                        name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'column',
                                    [
                                        abjad.MarkupCommand(
                                            'hcenter-in',
                                            12,
                                            [
                                                'Clarinet',
                                                abjad.MarkupCommand(
                                                    'line',
                                                    [
                                                        '(B',
                                                        abjad.MarkupCommand(
                                                            'hspace',
                                                            -0.5
                                                            ),
                                                        abjad.MarkupCommand(
                                                            'fontsize',
                                                            -3,
                                                            abjad.MarkupCommand(
                                                                'raise',
                                                                0.5,
                                                                abjad.MarkupCommand(
                                                                    'flat'
                                                                    )
                                                                )
                                                            ),
                                                        abjad.MarkupCommand(
                                                            'hspace',
                                                            -0.5
                                                            ),
                                                        ')',
                                                        ]
                                                    ),
                                                ]
                                            ),
                                        ]
                                    ),
                                ),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'column',
                                    [
                                        abjad.MarkupCommand(
                                            'hcenter-in',
                                            12,
                                            [
                                                'Cl.',
                                                abjad.MarkupCommand(
                                                    'line',
                                                    [
                                                        '(B',
                                                        abjad.MarkupCommand(
                                                            'hspace',
                                                            -0.5
                                                            ),
                                                        abjad.MarkupCommand(
                                                            'fontsize',
                                                            -3,
                                                            abjad.MarkupCommand(
                                                                'raise',
                                                                0.5,
                                                                abjad.MarkupCommand(
                                                                    'flat'
                                                                    )
                                                                )
                                                            ),
                                                        abjad.MarkupCommand(
                                                            'hspace',
                                                            -0.5
                                                            ),
                                                        ')',
                                                        ]
                                                    ),
                                                ]
                                            ),
                                        ]
                                    ),
                                ),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='treble',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[D3, Bb6]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch('bf'),
                        ),
                    abjad.instrumenttools.ClarinetInEFlat(
                        name='clarinet in E-flat',
                        short_name='cl. E-flat',
                        name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'column',
                                    [
                                        abjad.MarkupCommand(
                                            'hcenter-in',
                                            12,
                                            [
                                                'Clarinet',
                                                abjad.MarkupCommand(
                                                    'line',
                                                    [
                                                        '(E',
                                                        abjad.MarkupCommand(
                                                            'hspace',
                                                            -0.5
                                                            ),
                                                        abjad.MarkupCommand(
                                                            'fontsize',
                                                            -3,
                                                            abjad.MarkupCommand(
                                                                'raise',
                                                                0.5,
                                                                abjad.MarkupCommand(
                                                                    'flat'
                                                                    )
                                                                )
                                                            ),
                                                        abjad.MarkupCommand(
                                                            'hspace',
                                                            -0.5
                                                            ),
                                                        ')',
                                                        ]
                                                    ),
                                                ]
                                            ),
                                        ]
                                    ),
                                ),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'column',
                                    [
                                        abjad.MarkupCommand(
                                            'hcenter-in',
                                            12,
                                            [
                                                'Cl.',
                                                abjad.MarkupCommand(
                                                    'line',
                                                    [
                                                        '(E',
                                                        abjad.MarkupCommand(
                                                            'hspace',
                                                            -0.5
                                                            ),
                                                        abjad.MarkupCommand(
                                                            'fontsize',
                                                            -3,
                                                            abjad.MarkupCommand(
                                                                'raise',
                                                                0.5,
                                                                abjad.MarkupCommand(
                                                                    'flat'
                                                                    )
                                                                )
                                                            ),
                                                        abjad.MarkupCommand(
                                                            'hspace',
                                                            -0.5
                                                            ),
                                                        ')',
                                                        ]
                                                    ),
                                                ]
                                            ),
                                        ]
                                    ),
                                ),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='treble',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[F3, C7]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("ef'"),
                        ),
                    abjad.instrumenttools.BassClarinet(
                        name='bass clarinet',
                        short_name='bass cl.',
                        name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Bass clarinet'
                                    ),
                                ),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Bass cl.'
                                    ),
                                ),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='treble',
                                    ),
                                abjad.Clef(
                                    name='bass',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[Bb1, G5]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch('bf,'),
                        ),
                    ]
                ),
            ),
        abjad.instrumenttools.Performer(
            name='pianist',
            instruments=abjad.instrumenttools.InstrumentList(
                [
                    abjad.instrumenttools.Piano(
                        name='piano',
                        short_name='pf.',
                        name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Piano'
                                    ),
                                ),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Pf.'
                                    ),
                                ),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='treble',
                                    ),
                                abjad.Clef(
                                    name='bass',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[A0, C8]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    abjad.instrumenttools.Harpsichord(
                        name='harpsichord',
                        short_name='hpschd.',
                        name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Harpsichord'
                                    ),
                                ),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Hpschd.'
                                    ),
                                ),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='treble',
                                    ),
                                abjad.Clef(
                                    name='bass',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[C2, C7]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    ]
                ),
            ),
        abjad.instrumenttools.Performer(
            name='percussionist',
            instruments=abjad.instrumenttools.InstrumentList(
                [
                    abjad.instrumenttools.Percussion(
                        name='bass drum',
                        short_name='bass drum',
                        name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Bass drum'
                                    ),
                                ),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'B. dr.'
                                    ),
                                ),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='percussion',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[A0, C8]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    abjad.instrumenttools.Percussion(
                        name='crotales',
                        short_name='crotales',
                        name_markup=abjad.Markup(
                            contents=('Crotales',),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=('Crot.',),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='percussion',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[A0, C8]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    abjad.instrumenttools.Percussion(
                        name='scraped slate',
                        short_name='scraped slate',
                        name_markup=abjad.Markup(
                            contents=('Slate',),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=('Slt.',),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='percussion',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[A0, C8]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    abjad.instrumenttools.Percussion(
                        name='snare drum',
                        short_name='snare drum',
                        name_markup=abjad.Markup(
                            contents=('Snare drum',),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=('Sn. Dr.',),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='percussion',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[A0, C8]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    abjad.instrumenttools.Percussion(
                        name='sponges',
                        short_name='sponges',
                        name_markup=abjad.Markup(
                            contents=('Sponges',),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=('Spg.',),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='percussion',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[A0, C8]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    abjad.instrumenttools.Percussion(
                        name='suspended cymbal',
                        short_name='suspended cymbal',
                        name_markup=abjad.Markup(
                            contents=('Suspended cymbal',),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=('Sus. cym.',),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='percussion',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[A0, C8]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    abjad.instrumenttools.Percussion(
                        name='tam-tam',
                        short_name='tam-tam',
                        name_markup=abjad.Markup(
                            contents=('Tam-tam',),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=('Tam.',),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='percussion',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[A0, C8]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    abjad.instrumenttools.Xylophone(
                        name='xylophone',
                        short_name='xyl.',
                        name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Xylophone'
                                    ),
                                ),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Xyl.'
                                    ),
                                ),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='treble',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[C4, C7]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c''"),
                        ),
                    ]
                ),
            ),
        abjad.instrumenttools.Performer(
            name='violinist',
            instruments=abjad.instrumenttools.InstrumentList(
                [
                    abjad.instrumenttools.Violin(
                        name='violin',
                        short_name='vn.',
                        name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Violin'
                                    ),
                                ),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Vn.'
                                    ),
                                ),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='treble',
                                    ),
                                ]
                            ),
                        default_tuning=abjad.Tuning(
                            pitches=abjad.PitchSegment(
                                (
                                    abjad.NamedPitch('g'),
                                    abjad.NamedPitch("d'"),
                                    abjad.NamedPitch("a'"),
                                    abjad.NamedPitch("e''"),
                                    ),
                                item_class=abjad.NamedPitch,
                                ),
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[G3, G7]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    abjad.instrumenttools.Percussion(
                        name='scraped slate',
                        short_name='scraped slate',
                        name_markup=abjad.Markup(
                            contents=('Untuned percussion',),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=('Perc.',),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='percussion',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[A0, C8]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    ]
                ),
            ),
        abjad.instrumenttools.Performer(
            name='violist',
            instruments=abjad.instrumenttools.InstrumentList(
                [
                    abjad.instrumenttools.Viola(
                        name='viola',
                        short_name='va.',
                        name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Viola'
                                    ),
                                ),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Va.'
                                    ),
                                ),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='alto',
                                    ),
                                abjad.Clef(
                                    name='treble',
                                    ),
                                ]
                            ),
                        default_tuning=abjad.Tuning(
                            pitches=abjad.PitchSegment(
                                (
                                    abjad.NamedPitch('c'),
                                    abjad.NamedPitch('g'),
                                    abjad.NamedPitch("d'"),
                                    abjad.NamedPitch("a'"),
                                    ),
                                item_class=abjad.NamedPitch,
                                ),
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[C3, D6]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    ]
                ),
            ),
        abjad.instrumenttools.Performer(
            name='cellist',
            instruments=abjad.instrumenttools.InstrumentList(
                [
                    abjad.instrumenttools.Cello(
                        name='cello',
                        short_name='vc.',
                        name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Cello'
                                    ),
                                ),
                            ),
                        short_name_markup=abjad.Markup(
                            contents=(
                                abjad.MarkupCommand(
                                    'hcenter-in',
                                    12,
                                    'Vc.'
                                    ),
                                ),
                            ),
                        allowable_clefs=abjad.instrumenttools.ClefList(
                            [
                                abjad.Clef(
                                    name='bass',
                                    ),
                                abjad.Clef(
                                    name='tenor',
                                    ),
                                abjad.Clef(
                                    name='treble',
                                    ),
                                ]
                            ),
                        default_tuning=abjad.Tuning(
                            pitches=abjad.PitchSegment(
                                (
                                    abjad.NamedPitch('c,'),
                                    abjad.NamedPitch('g,'),
                                    abjad.NamedPitch('d'),
                                    abjad.NamedPitch('a'),
                                    ),
                                item_class=abjad.NamedPitch,
                                ),
                            ),
                        pitch_range=abjad.PitchRange(
                            range_string='[C2, G5]',
                            ),
                        middle_c_sounding_pitch=abjad.NamedPitch("c'"),
                        ),
                    ]
                ),
            ),
        ]
    )
