import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Wind_Section_Staff_Group',
                'Oboe_Music_Staff',
                'Oboe_Music_Voice',
                'Oboe_Rest_Voice',
                'Clarinet_Music_Staff',
                'Clarinet_Music_Voice',
                'Clarinet_Rest_Voice',
                'Percussion_Section_Staff_Group',
                'Piano_Music_Staff',
                'Piano_Music_Voice',
                'Piano_Rest_Voice',
                'Percussion_Music_Staff',
                'Percussion_Music_Voice',
                'Percussion_Rest_Voice',
                'String_Section_Staff_Group',
                'Violin_Music_Staff',
                'Violin_Music_Voice',
                'Violin_Rest_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Viola_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        ('duration', "1'36''"),
        (
            'fermata_measure_numbers',
            [
                89,
                93,
                95,
                97,
                99,
                101,
                103,
                105,
                107,
                109,
                117,
                119,
                ],
            ),
        ('final_measure_number', 132),
        ('first_measure_number', 89),
        ('segment_name', 'B'),
        ('segment_number', 3),
        ('start_clock_time', "3'24''"),
        ('stop_clock_time', "5'00''"),
        (
            'time_signatures',
            [
                '3/4',
                '11/8',
                '5/8',
                '4/4',
                '1/4',
                '2/4',
                '1/4',
                '7/4',
                '1/4',
                '4/4',
                '1/4',
                '7/8',
                '1/4',
                '7/8',
                '1/4',
                '8/4',
                '1/4',
                '4/4',
                '1/4',
                '3/4',
                '1/4',
                '4/4',
                '5/8',
                '9/8',
                '5/4',
                '2/4',
                '3/4',
                '3/4',
                '1/4',
                '3/4',
                '1/4',
                '5/4',
                '13/8',
                '3/4',
                '5/8',
                '9/8',
                '9/8',
                '9/8',
                '5/8',
                '3/4',
                '3/4',
                '4/4',
                '4/4',
                '5/4',
                ],
            ),
        ]
    )
