import abjad


metadata = abjad.OrderedDict(
    [
        ('duration', "1'40''"),
        ('final_measure_number', 234),
        ('first_measure_number', 200),
        ('segment_name', 'E'),
        ('segment_number', 6),
        ('start_clock_time', "9'33''"),
        ('stop_clock_time', "11'13''"),
        (
            'time_signatures',
            [
                '3/4',
                '4/4',
                '6/4',
                '9/8',
                '3/4',
                '5/8',
                '9/8',
                '9/8',
                '5/8',
                '5/8',
                '3/4',
                '4/4',
                '5/4',
                '5/4',
                '3/4',
                '3/4',
                '4/4',
                '11/8',
                '3/4',
                '5/8',
                '9/8',
                '9/8',
                '7/8',
                '9/8',
                '3/4',
                '3/4',
                '3/4',
                '3/4',
                '4/4',
                '5/4',
                '4/4',
                '9/8',
                '3/4',
                '5/8',
                '9/8',
                ],
            ),
        ]
    )
