# -*- encoding: utf-8 -*-
from abjad.tools import indicatortools


time_signature_inventory = [
    [
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((6, 4)),
        indicatortools.TimeSignature((7, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((7, 4)),
        indicatortools.TimeSignature((11, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((6, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((8, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((6, 4)),
        indicatortools.TimeSignature((7, 4)),
        indicatortools.TimeSignature((7, 4)),
        ],
    [
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((11, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((7, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((8, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((13, 8)),
        ],
    [
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 4)),
        ],
    [
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        ],
    [
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((6, 4)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((11, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        ],
    [
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((6, 4)),
        indicatortools.TimeSignature((7, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((7, 4)),
        indicatortools.TimeSignature((11, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((6, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((7, 8)),
        ],
    [
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((8, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((9, 8)),
        ],
    [
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((6, 4)),
        indicatortools.TimeSignature((7, 4)),
        indicatortools.TimeSignature((7, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((11, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((7, 4)),
        ],
    [
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((8, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((13, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((9, 8)),
        ],
    [
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((6, 4)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((11, 8)),
        ],
    [
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((7, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 4)),
        ],
    [
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((9, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((5, 8)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((3, 4)),
        ],
    ]