import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Wind_Section_Staff_Group',
                'Oboe_Music_Staff',
                'Oboe_Music_Voice',
                'Oboe_Rest_Voice',
                'Clarinet_Music_Staff',
                'Clarinet_Music_Voice',
                'Clarinet_Rest_Voice',
                'Percussion_Section_Staff_Group',
                'Piano_Music_Staff',
                'Piano_Music_Voice',
                'Piano_Rest_Voice',
                'Percussion_Music_Staff',
                'Percussion_Music_Voice',
                'Percussion_Rest_Voice',
                'String_Section_Staff_Group',
                'Violin_Music_Staff',
                'Violin_Music_Voice',
                'Violin_Rest_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'Viola_Rest_Voice',
                'Cello_Music_Staff',
                'Cello_Music_Voice',
                'Cello_Rest_Voice',
                ],
            ),
        ('duration', "0'27''"),
        ('final_measure_number', 290),
        ('first_measure_number', 281),
        ('segment_name', 'H'),
        ('segment_number', 9),
        ('start_clock_time', "13'01''"),
        ('stop_clock_time', "13'28''"),
        (
            'time_signatures',
            [
                '7/8',
                '6/4',
                '7/4',
                '7/4',
                '3/4',
                '11/8',
                '5/8',
                '4/4',
                '2/4',
                '7/4',
                ],
            ),
        ]
    )
