# -*- encoding: utf-8 -*-
from abjad import *


segment_time_signatures = datastructuretools.TypedOrderedDict(
    [
        (
            'B',
            [
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((7, 8)),
                indicatortools.TimeSignature((6, 4)),
                indicatortools.TimeSignature((7, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((7, 4)),
                indicatortools.TimeSignature((11, 8)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((7, 8)),
                indicatortools.TimeSignature((6, 4)),
                indicatortools.TimeSignature((7, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((7, 4)),
                indicatortools.TimeSignature((11, 8)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((6, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((7, 8)),
                indicatortools.TimeSignature((7, 8)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((8, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((5, 4)),
                indicatortools.TimeSignature((2, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((7, 8)),
                indicatortools.TimeSignature((6, 4)),
                indicatortools.TimeSignature((7, 4)),
                indicatortools.TimeSignature((7, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((11, 8)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((2, 4)),
                indicatortools.TimeSignature((7, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((7, 8)),
                indicatortools.TimeSignature((7, 8)),
                indicatortools.TimeSignature((8, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((5, 4)),
                indicatortools.TimeSignature((2, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((5, 4)),
                indicatortools.TimeSignature((13, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((5, 4)),
                ],
            ),
        (
            'E',
            [
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((7, 8)),
                indicatortools.TimeSignature((5, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((6, 4)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((5, 4)),
                indicatortools.TimeSignature((5, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((11, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((7, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((5, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((9, 8)),
                ],
            ),
        (
            'K',
            [
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((7, 8)),
                indicatortools.TimeSignature((5, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((6, 4)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((5, 4)),
                indicatortools.TimeSignature((5, 4)),
                indicatortools.TimeSignature((1, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((11, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((7, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((11, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((7, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((11, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((7, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((1, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((5, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((5, 4)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((3, 4)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((9, 8)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((5, 8)),
                indicatortools.TimeSignature((4, 4)),
                indicatortools.TimeSignature((5, 4)),
                indicatortools.TimeSignature((3, 4)),
                ],
            ),
        ]
    )